### ISSUE TITLE
32-bit x86 too

### ISSUE THREAD

**Issue by KOLANICH** [beerisgood/Notepad-plus-plus-integrity_stuff#1]

**Comment by beerisgood** [comment]
Okay will add it at Weekend (i'm on work until friday and only online at mobile)

**Comment by beerisgood** [comment]
@KOLANICH Done. See https://github.com/beerisgood/Notepad-plus-plus-integrity_stuff/releases/tag/7.5.7_x86

**Comment by KOLANICH** [comment]
Thank you.
